# Generated by Django 2.2.1 on 2019-06-01 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='td_formulario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('senha', models.CharField(max_length=20)),
                ('notificacao', models.BooleanField()),
                ('avaliacao', models.CharField(choices=[('Excelente', 10), ('Bom', 8), ('Médio', 5), ('Ruim', 3), ('Péssimo', 1)], max_length=5)),
                ('comentarios', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
    ]
