# Generated by Django 2.2.1 on 2019-06-01 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuario',
            new_name='TB_Usuario',
        ),
        migrations.DeleteModel(
            name='td_formulario',
        ),
        migrations.AlterModelTable(
            name='tb_usuario',
            table='TB_Usuarios',
        ),
    ]
