# Generated by Django 2.2.2 on 2019-06-03 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190601_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_usuario',
            name='avaliacao',
            field=models.CharField(max_length=5),
        ),
    ]
