# Generated by Django 2.2 on 2019-06-03 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190603_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_usuario',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
