# Generated by Django 2.2.2 on 2019-06-04 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190603_0916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tb_usuario',
            name='id',
        ),
        migrations.AddField(
            model_name='tb_usuario',
            name='cpf',
            field=models.CharField(default='', max_length=11, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tb_usuario',
            name='avaliacao',
            field=models.CharField(choices=[('Excelente', 'Excelente'), ('Bom', 'Bom'), ('Médio', 'Médio'), ('Ruim', 'Ruim'), ('Péssimo', 'Péssimo')], max_length=10),
        ),
    ]
