# Generated by Django 2.2.2 on 2019-06-04 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190604_1000'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tb_usuario',
            table='TB_Usuario',
        ),
    ]
