# Generated by Django 2.2 on 2019-06-03 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190603_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_usuario',
            name='avaliacao',
            field=models.CharField(choices=[('Excelente', 'Excelente'), ('Bom', 'Bom'), ('Médio', 'Médio'), ('Ruim', 'Ruim'), ('Péssimo', 'Péssimo')], max_length=10),
        ),
        migrations.AlterField(
            model_name='tb_usuario',
            name='id',
            field=models.CharField(max_length=11, primary_key=True, serialize=False),
        ),
    ]
