# Generated by Django 2.2.1 on 2019-06-07 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190604_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='TB_Autor',
            fields=[
                ('cpf', models.CharField(max_length=11, primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(max_length=60)),
                ('nacionalidade', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'TB_Autor',
            },
        ),
        migrations.CreateModel(
            name='TB_Livro',
            fields=[
                ('isbn', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(max_length=80)),
                ('editora', models.CharField(max_length=100)),
                ('descricao', models.TextField(max_length=500)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.TB_Autor')),
            ],
            options={
                'db_table': 'TB_Livro',
            },
        ),
        migrations.DeleteModel(
            name='TB_Usuario',
        ),
    ]
